/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_1.h"
#include "UART_1_SPI_UART.h"
#include "UART_1_PINS.h"
#include "UART_1_SPI_UART_PVT.h"
#include "UART_1_PVT.h"
#include "UART_1_BOOT.h"
#include "DS_Pin.h"
#include "DS_Pin_aliases.h"
#include "SHCP_Pin.h"
#include "SHCP_Pin_aliases.h"
#include "STCP_Pin.h"
#include "STCP_Pin_aliases.h"
#include "MR_Pin.h"
#include "MR_Pin_aliases.h"
#include "OE_Pin.h"
#include "OE_Pin_aliases.h"
#include "Q0_Pin.h"
#include "Q0_Pin_aliases.h"
#include "Q1_Pin.h"
#include "Q1_Pin_aliases.h"
#include "Q2_Pin.h"
#include "Q2_Pin_aliases.h"
#include "Q3_Pin.h"
#include "Q3_Pin_aliases.h"
#include "Q4_Pin.h"
#include "Q4_Pin_aliases.h"
#include "Q5_Pin.h"
#include "Q5_Pin_aliases.h"
#include "Q6_Pin.h"
#include "Q6_Pin_aliases.h"
#include "Q7_Pin.h"
#include "Q7_Pin_aliases.h"
#include "LED_OK.h"
#include "LED_OK_aliases.h"
#include "LED_ERROR.h"
#include "LED_ERROR_aliases.h"
#include "UART_1_SCBCLK.h"
#include "UART_1_tx.h"
#include "UART_1_tx_aliases.h"
#include "UART_1_rx.h"
#include "UART_1_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

